### ISSUE TITLE
Unexpected behaviour when only one cursor is left

### ISSUE THREAD

**Issue by semiaddict** [fajran/npTuioClient#5]
Hi,

I'm using Touch2TUIO to translate the Windows7 touch events to TUIO, and then using npTuioClient in Chrome to access the TUIO messages using Javascript.

When only one cursor is left on the screen, I get unexpected results.
1) If the fingure is removed, the cursor stays on the screen (no remove cursor callback is called). 
2) if I keep the fingure touched, I see some activity in the Touch2TUIO window, but nothing comes through to the js callback.

Any idea what might be causing this ?

**Comment by semiaddict** [comment]
After some more digging, I found out that this was a bug in Touch2TUIO...

**Comment by fajran** [comment]
OK. Thanks for the report anyway!

**Comment by skhameneh** [comment]
I've found the bug in Touch2Tuio and will be resurrecting an improved version on Github soon.
This wont "fix" the issue per say, but you can work around it by removing:
if (msg->wParam == TIMER_IDENTIFIER)

in function "GetMsgProc" under:
case WM_TIMER:

The conditional is incorrect, and removing it will allow the timer to run and remove the last cursor.
