### ISSUE TITLE
npTuioClient does not function on Mac OSX 10.8.1 or 10.8.2

### ISSUE THREAD

**Issue by hillct** [fajran/npTuioClient#8]
After upgrade to OS 10.8.1, I found that npTuioClient would no longer operate. I re-downloaded the existing mac binary and reinstalled with no success. I grabbed the source, and rebuilt it using XCode 4.5.2 which initially failed, but the only reported error was a conflicting type definition within the new MacOS SDK, so I commented out the definition in source, and it built suvvessfully. The Diff can be found below, though this did allow it to build, It still wouldn't load and run in any of Chrome, Firefox or Safari

Diff below (would have cloned and patched, but it isn't a fix, and it's one line):

diff --git a/npapi/protypes.h b/npapi/protypes.h
index 4405bfc..4814834 100644
--- a/npapi/protypes.h
+++ b/npapi/protypes.h
@@ -105,7 +105,7 @@ typedef PRUintn uint;
  */

 #if !defined(XP_BEOS) && !defined(VMS)
-typedef PRUint64 uint64;
+// typedef PRUint64 uint64;
 #endif

 /*

**Comment by fajran** [comment]
Hi, I just made an update to the plugin. I tested it works on Chrome on Mac but unfortunately still does not work on Safari nor Firefox. 

The code is under the "cleanup" branch https://github.com/fajran/npTuioClient/tree/cleanup
the binary is here https://github.com/downloads/fajran/npTuioClient/npTuioClient-1.5b1-osx.zip

could you test it?

**Comment by borismus** [comment]
Just tested it on my Mac and everything works swimmingly! Thanks for this update, Fajran.

**Comment by fajran** [comment]
great! now the issue is how to make it also works with Safari and Firefox. I tried to follow debugging steps from [FireBreath](http://www.firebreath.org/display/documentation/Debugging+Plugins) but every time I attach the debugger, the plugin process just get closed.

**Comment by hillct** [comment]
I concur. Thanks. Looking great in Chrome once again. While certainly this is minor, and of near no consequence in a test release, the build package name has the suffix .bundle rather than .plugin which I mention only so it doesn't go to a release with that name.

**Comment by fajran** [comment]
A i386 only plugin apparently does not make Safari and Firefox crash
