### ISSUE TITLE
Could not load npTuioClient on Mac OS X

### ISSUE THREAD

**Issue by borismus** [fajran/npTuioClient#9]
I can't get the latest version (0.2) to work in Chrome 30.0.1599.66 (Oct 2 2013) on Mac OS X 10.8.5.

The error is "Could not load npTuioClient".

**Comment by fajran** [comment]
Have you tried the one from the [cleanup branch](https://github.com/fajran/npTuioClient/tree/cleanup)? I still haven't made the binaries tho

**Comment by fajran** [comment]
Please try this one https://fajran.s3.amazonaws.com/github/npTuioClient/npTuioClient-1.5b2-mac.zip I tried with Chrome 30.0.1599.66 on Mac OS X 10.7.5

**Comment by borismus** [comment]
Thanks, that works for me. Can you make this the official release?

**Comment by fajran** [comment]
I just realized that there is release feature on GitHub. I have released it there https://github.com/fajran/npTuioClient/releases/tag/v1.5b2

Now I am closing this issue. Thanks for the report.

**Comment by wdevore** [comment]
Has anyone been able to get this to work on Mavericks (10.9)? Thanks.
